# Experiment name - QAT for MobileNetV2 on CIFAR10 using NUDE
name: mobilenetv2_cifar_nude_bfat_v6

# Name of output directory. Checkpoints and logs will be saved at `pwd`/output_dir
output_dir: training
training_device: gpu

num_random_path: 1
split_aw_cands: false 
target_bits: [6, 5, 4, 3, 2]
post_training_batchnorm_calibration: true
information_distortion_mitigation: false
enable_dynamic_bit_training: false
kd: false

# Dataset loader
dataloader:
  dataset: cifar10
  num_classes: 10
  path: ./data
  batch_size: 128  # Per GPU (Total batch size will be 128 * 4 = 512)
  workers: 12
  deterministic: true

# 🌟 Crucial: Loading your pre-trained floating point model
resume:
  # path: training/mobilenetv2_cifar_pretrain/mobilenetv2_cifar_pretrain_best.pth.tar
  # lean: true  # Must be true to initialize QAT from FP weights and ignore optimizer state
  path: training/mb_c10_pretrain/mb_c10_pretrain_checkpoint.pth.tar
  lean: true

log:
  num_best_scores: 3
  print_freq: 50

#============================ Model ============================================

arch: mobilenet_v2_cifar
pre_trained: false

#============================ Quantization =====================================

# (default for all layers)
quan:
  act: 
    mode: lsq
    bit: 2
    per_channel: false
    symmetric: false
    all_positive: true

  weight: 
    mode: lsq
    bit: 2
    per_channel: false
    symmetric: false
    all_positive: false
  
  excepts:
    # We follow the standard ImageNet setting: first and last layers are usually higher precision or handled separately
    # In this codebase, 'excepts' can specify fixed bit widths (defaulting to 8-bit usually)
    features.0.0:
      act:
        bit: 
        all_positive: false
      weight:
        bit: 
    features.0.1:
      act:
        bit: 
      weight:
        bit:
    classifier.1:
      act:
        bit: 
      weight:
        bit:

#============================ Training / Evaluation ============================

eval: false

epochs: 200
smoothing: 0
scale_gradient: false
dropout: 0.2

opt: sgd
lr: 0.04  # Lower learning rate for QAT
momentum: 0.9
weight_decay: 0.000025

sched: cosine
min_lr: 0.00001
decay_rate: 0.1
warmup_epochs: 0
warmup_lr: 0.00001
decay_epochs: 30
cooldown_epochs: 0

ema_decay: 0.9997

bfat:
  enabled: false
  dual_bit: false
  use_restricted_as_base: true # 一阶段加噪开关
  all_bits: true              # 二阶段全位注入：如果为 true，则对参数的所有位注入故障
  
  ber: 0.02                   # 二阶段all_bits普适注入率
  ber_base_restricted: 0.01   # 一阶段注入率
  ber_msb: 0.02               # 二阶段MSB独立注入率
  
  loss_weight: 1.0
  loss_type: "direct_ce"
  projection_base: "combined"
  limit_norm: false
  weight_relative_limit: false
  weight_limit_ratio: 0.5
  norm_ratio: 1.0
  
  freeze_bn: false
  projection_mode: "orthogonal" # orthogonal: 强行正交，direction: 方向修正，cagrad: 寻找最佳妥协方向，none: 不进行投影
