# Experiment name
name: alexnet

# Name of output directory. Checkpoints and logs will be saved at `pwd`/output_dir
output_dir: training
training_device: gpu

num_random_path: 3
target_bits: [8]
post_training_batchnorm_calibration: true
information_distortion_mitigation: false
enable_dynamic_bit_training: true
kd: false

# Dataset loader
dataloader:
  dataset: imagenet
  num_classes: 1000
  path: /data/imagenet
  batch_size: 32
  workers: 8
  deterministic: true

resume:
  path:
  lean: false

log:
  num_best_scores: 1
  print_freq: 20

#============================ Model ============================================

arch: alexnet
pre_trained: true

#============================ Quantization =====================================

# (default for all layers)
quan:
  act:
    mode: lsq
    bit: 2
    per_channel: false
    symmetric: false
    all_positive: true

  weight:
    mode: lsq
    bit: 2
    per_channel: false
    symmetric: false
    all_positive: false

  excepts:
    excepts_bits_width: 8
    # Specify quantized bit width for some layers, like this:
    features.0:
      act:
        bit:
        all_positive: false
      weight:
        bit:
    classifier.0:
      act:
        bit:
      weight:
        bit:
    classifier.2:
      act:
        bit:
      weight:
        bit:
    classifier.4:
      act:
        bit:
      weight:
        bit:

#============================ Training / Evaluation ============================

eval: false

epochs: 200
smoothing: 0.0
scale_gradient: false

opt: sgd
lr: 0.001
momentum: 0.9
weight_decay: 0.000025
adaptive_region_weight_decay: 0

sched: cosine
min_lr: 0.00001
decay_rate: 0.1
warmup_epochs: 5
warmup_lr: 0.00001
decay_epochs: 30
cooldown_epochs: 0

ema_decay: 0.99